<?xml version="1.0"?>
<package format="3">
  <name>mine_lidar_mapping</name>
  <version>0.1.0</version>
  <description>LiDAR spatial mapping demo for SIH mine safety project</description>
  <maintainer email="you@example.com">Arnav</maintainer>
  <license>MIT</license>
  <exec_depend>rplidar_ros</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
